ProjectStudentManagement/ProjectStudentManagement/Controllers/EmployeesController.cs
using DAO;
using DTO;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ProjectStudentManagement.Controllers
{
    public class EmployeesController : Controller
    {
        #region Index
        //
        // GET: /Employees/
        public ActionResult Index()
        {
            //Kiểm tra xem người dùng có được xem(truy cập vào chức năng)
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLND_V") == false)
            {
                return RedirectToAction("Login", "Home");
            }

            //Kiểm tra xem người dùng có được phép thêm
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLND_I") == false)
            {
                ViewBag.InsertPermission = false;
            }

            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            return View();
        }

        [HttpPost]
        public ActionResult SearchEmployees(string strKeyWord, int intPageIndex = 0)
        {
            try
            {
                //Lấy cấu hình số dòng trên trang
                //int intPageSize = Convert.ToInt32(ConfigurationManager.AppSettings["RowPerPage"]);
                //Lấy config số trang hiển thị trên thanh phân trang
                int intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);
                int intTotalPages = 0;
                int intTotalRows = 0;

                //Gen HTML
                StringBuilder strHTMLEmployees = new StringBuilder();

                DataTable dtbEmployees = new EmployeesDAO().SearchEmployees(strKeyWord, intPageIndex, intVisiblePages);

                if (dtbEmployees != null && dtbEmployees.Rows.Count > 0)
                {
                    strHTMLEmployees = GenHTMLEmployees(dtbEmployees);
                    //Lấy tổng số lưởng dòng
                    intTotalRows = Convert.ToInt32(dtbEmployees.Rows[0]["TotalRows"]);
                    //Lấy tổng số lượng trang
                    intTotalPages = intTotalRows / intVisiblePages;
                    //Trường hợp số phần tử không chia hết cho intVisiblePages
                    if (intTotalRows % intVisiblePages != 0)
                        intTotalPages = intTotalPages + 1;
                }
                else
                {
                    strHTMLEmployees.Append("<tr><td colspan='12' class='table-content-null'>Hiện không có nội dung</td></tr>");
                }

                return Json(new
                {
                    iserror = false,
                    content = Convert.ToString(strHTMLEmployees),
                    totalpages = intTotalPages,
                    totalrows = intTotalRows
                });
            }
            catch
            {
                return Json(new { iserror = true });
            }
        }

        private StringBuilder GenHTMLEmployees(DataTable dtbPermission)
        {
            bool bPerEdit = true;
            bool bPerDelete = true;
            //Kiểm tra người dùng được xóa
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLND_D") == false)
            {
                bPerDelete = false;
            }


            int intCountRow = dtbPermission.Rows.Count;
            StringBuilder strHTMLEmployees = new StringBuilder();

            for (int i = 0; i < intCountRow; i++)
            {
                string strEmloyeeID = Convert.ToString(dtbPermission.Rows[i]["EmployeeID"]).Trim();

                strHTMLEmployees.Append("<tr>");
                strHTMLEmployees.AppendFormat("<td>{0}</td>", dtbPermission.Rows[i]["STT"]);
                strHTMLEmployees.AppendFormat("<td>{0}</td>", strEmloyeeID);
                strHTMLEmployees.AppendFormat("<td>{0}</td>", dtbPermission.Rows[i]["FullName"]);
                string sEdit = "";
                string sDelete = "";
                if (bPerEdit != false)
                {
                    sEdit += "<span class='glyphicon glyphicon-pencil table-icon' data-name='Detail'></span>";
                }

                if (bPerDelete != false)
                {
                    sDelete += "<span class='glyphicon glyphicon-trash table-icon' data-name='Delete'></span>";
                }
                strHTMLEmployees.AppendFormat("<td data-employeeid='{0}'>" + sEdit + sDelete + "</td>", strEmloyeeID);

                strHTMLEmployees.Append("</tr>");
            }

            return strHTMLEmployees;
        }
        #endregion

        #region Delete
        [HttpPost]
        public JsonResult DeleteEmployees(string strEmployeeID)
        {
            try
            {
                bool bolSuccess = new EmployeesDAO().DeleteEmployees(strEmployeeID);

                if (bolSuccess == false)
                    return Json(new { iserror = true});

                return Json(new { iserror = false });
            }
            catch (Exception)
            {
                return Json(new { iserror = true });
            }
        }
        #endregion

        #region Insert
        public ActionResult EmployeesInsert()
        {
            //Kiểm tra xem người dùng có được phép thêm
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLND_I") == false)
            {
                return RedirectToAction("Login", "Home");
            }
            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            return View();
        }

        [HttpPost]
        public JsonResult InsertEmployees(FormCollection frm)
        {
            try
            {
                string strLastName = Convert.ToString(frm["tbxHo"]);
                string strFirstName = Convert.ToString(frm["tbxTen"]);
                string strAddress = Convert.ToString(frm["tbxAddress"]);
                string strDistrict = Convert.ToString(frm["tbxDistrict"]);
                string strCity = Convert.ToString(frm["tbxCity"]);
                string strSDT = Convert.ToString(frm["tbxSDT"]);
                string strEmail = Convert.ToString(frm["tbxEmail"]);
                string strRole = Convert.ToString(frm["sltKeyWordRole"]);
                string strPass = Convert.ToString(frm["tbxPass"]);

                bool bolSuccess = new EmployeesDAO().InsertEmployees(strLastName, strFirstName, strAddress, strDistrict, strCity, strSDT, strEmail, strRole, strPass);

                if (bolSuccess == false)
                    return Json(new { iserror = true });

                return Json(new { iserror = false });
            }
            catch (Exception)
            {
                return Json(new { iserror = true });
            }
        }
        #endregion

        #region Detail
        public ActionResult EmployeesDetail(string strEmployeeID)
        {
            //Kiểm tra xem người dùng có được phép thêm
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLND_U") == false)
            {
                ViewBag.UpdatePermission = false;
            }
            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            EmployeesDTO EDTO = new EmployeesDAO().GetEmployeesByID(strEmployeeID);
            return View(EDTO);
        }
        #endregion

        #region Update
        public ActionResult EmployeesUpdate(string strEmployeeID)
        {
            //EmployeesUpdate
            //Kiểm tra xem người dùng có được phép sửa
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLND_U") == false)
            {
                return RedirectToAction("Login", "Home");
            }
            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            EmployeesDTO EDTO = new EmployeesDAO().GetEmployeesByID(strEmployeeID);
            return View(EDTO);
        }


        public ActionResult UpdateEmployee(FormCollection frm)
        {
            try
            {
                string strEmployeeID = Convert.ToString(frm["tbxMGV"]);
                string strLastName = Convert.ToString(frm["tbxHo"]);
                string strFirstName = Convert.ToString(frm["tbxTen"]);
                string strAddress = Convert.ToString(frm["tbxAddress"]);
                string strDistrict = Convert.ToString(frm["tbxDistrict"]);
                string strCity = Convert.ToString(frm["tbxCity"]);
                string strSDT = Convert.ToString(frm["tbxSDT"]);
                string strEmail = Convert.ToString(frm["tbxEmail"]);
                string strRole = Convert.ToString(frm["sltKeyWordRole"]);

                bool bolSuccess = new EmployeesDAO().UpdateEmployees(strEmployeeID,strLastName, strFirstName, strAddress, strDistrict, strCity, strSDT, strEmail, strRole);

                if (bolSuccess == false)
                    return Json(new { iserror = true });

                return Json(new { iserror = false });
            }
            catch (Exception)
            {
                return Json(new { iserror = true });
            }
        }
        #endregion

        #region Helper
        [HttpPost]
        public ActionResult GetRole()
        {

            try
            {
                DataTable dtbQuery = new EmployeesDAO().GetRoleList();
                string sRoleList = JsonConvert.SerializeObject(dtbQuery);
                return Json(new { iserror = false, Rolelistcontent = sRoleList });
            }
            catch
            {

ProjectStudentManagement/ProjectStudentManagement/Views/Employees/EmployeesDetail.cshtml
@model DTO.EmployeesDTO
@{
    ViewBag.Title = "Chi tiết giáo viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Chi tiết giáo viên</h4>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="form-group">
            <div class="form-inline">
                <input type="hidden" id="hdEmployeeID" value="@(Model.EmployeesID)" />
                <label class="header-control col-sm-2">Mã giáo viên: </label>
                <label class="header-control col-sm-9">@(Model.EmployeesID)</label>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="form-group">
            <div class="form-inline">
                <label class="header-control col-sm-2">Họ Tên: </label>
                <label class="header-control col-sm-9">@(Model.strLastName) @(Model.strFirstName)</label>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="form-group">
            <div class="form-inline">
                <label class="header-control col-sm-2">Địa chỉ: </label>
                <label class="header-control col-sm-9">@(Model.strAddress) @(Model.strDistrict) @(Model.strCity)</label>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="form-group">
            <div class="form-inline">
                <label class="header-control col-sm-2">Số điện thoại: </label>
                <label class="header-control col-sm-9">@(Model.strSDT)</label>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="form-group">
            <div class="form-inline">
                <label class="header-control col-sm-2">Email: </label>
                <label class="header-control col-sm-9">@(Model.strEmail)</label>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="form-group">
            <div class="form-inline">
                <label class="header-control col-sm-2">Chức vụ: </label>
                <label class="header-control col-sm-9">@(Model.strRole)</label>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="row area-control">
        <div class="form-inline group-submit">
            @if (ViewBag.UpdatePermission != false)
            {
                <button type="button" class="btn btn-primary" id="btnEdit" onclick="EditEmployees();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-pencil"></i>Chỉnh sửa</button>
                    
            }

            <button type="button" class="btn btn-default" id="btnBack" onclick="BackManage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
        </div>
    </div>
</div>            

             



@section Scripts
{
    @*<script type="text/javascript">
            var visiblePages = "@ViewBag.intVisiblePages";
        </script>*@
    <script src="~/Scripts/CustomScripts/Employees/DetailEmloyees.js"></script>
}

ProjectStudentManagement/ProjectStudentManagement/Views/Employees/EmployeesInsert.cshtml
@{
    ViewBag.Title = "Thêm giáo viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-blue">
    <div class="panel-heading">
        Thêm giáo viên
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-6">
                @using (Html.BeginForm("InsertEmployees", "Employees", FormMethod.Post, new { @id = "frmEmployeesInsert" }))
                {
                    <input type="hidden" id="hdFormType" name="hdFormType" value="Insert" />
                    <div class="col-lg-12">
                        <div class="form-group col-lg-6">

                            <label>Họ:</label>
                            <input class="form-control col-lg-6" name="tbxHo" id="tbxHo" value="">
                        </div>
                        <div class="form-group col-lg-6">

                            <label>Tên:</label>
                            <input class="form-control col-lg-6" name="tbxTen" id="tbxTen" value="">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group col-lg-4">

                            <label>Địa chỉ:</label>
                            <input class="form-control col-lg-4" name="tbxAddress" id="tbxAddress" value="">
                        </div>
                        <div class="form-group col-lg-4">

                            <label>Tên đường:</label>
                            <input class="form-control col-lg-4" name="tbxDistrict" id="tbxDistrict" value="">
                        </div>
                        <div class="form-group col-lg-4">

                            <label>Thành phố:</label>
                            <input class="form-control col-lg-4" name="tbxCity" id="tbxCity" value="">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group col-lg-6">

                            <label>Số điện thoại:</label>
                            <input class="form-control" id="tbxSDT" name="tbxSDT" value="">
                        </div>

                        <div class="form-group col-lg-6">

                            <label>Email:</label>
                            <input class="form-control" id="tbxEmail" name="tbxEmail" value="">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group col-lg-6">

                            <label>Chức vụ:</label>
                            <select class="form-control" name="sltKeyWordRole" id="sltKeyWordRole">
                                <option disabled='disabled' selected='selected'>--Xin lựa chọn chức vụ--</option>
                            </select>
                        </div>

                        <div class="form-group col-lg-6">

                            <label>Mật khẩu:</label>
                            <input class="form-control" type="password" name="tbxPass" id="tbxPass" value="">
                        </div>
                    </div>
                    
                    <div class="col-lg-12">
                        <div class="form-group col-lg-6">
                            <button type="submit" class="btn btn-primary" id="btnXacNhan" onclick="return validationform()" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-check"></i>Xác nhận</button>
                        </div>
                        <div class="form-group col-lg-6">
                            <button type="button" class="btn btn-default" id="btnBack" onclick="BackManage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
                        </div>
                        

                    </div>
                }
            </div>

        </div>
        <!-- /.row (nested) -->
    </div>
    <!-- /.panel-body -->
</div>


@section Scripts
{
    <script type="text/javascript">
        var visiblePages = "@ViewBag.intVisiblePages";
    </script>

    <script src="~/Scripts/CustomScripts/Employees/InsertUpdateEmloyees.js"></script>
}

ProjectStudentManagement/ProjectStudentManagement/Views/Employees/EmployeesUpdate.cshtml
@model DTO.EmployeesDTO
@{
    ViewBag.Title = "Cập nhật giáo viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-blue">
    <div class="panel-heading">
        Sửa giáo viên
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-6">
                @using (Html.BeginForm("UpdateEmployee", "Employees", FormMethod.Post, new { @id = "frmEmployeesUpdate" }))
                {
                    <input type="hidden" id="hdFormType" name="hdFormType" value="Update" />
                <input type="hidden" id="RoleIDhidden" name="RoleIDhidden" value="@(Model.strRoleID)" />
                    <input type="hidden" id="hdEmployeeID" value="@(Model.EmployeesID)" />
                    <div class="col-lg-12">
                        <div class="form-group col-lg-12">

                            <label>Mã giáo viên:</label>
                            <input class="form-control col-lg-12" name="tbxMGV" id="tbxMGV" readonly value="@(Model.EmployeesID)">
                        </div>
                    </div>
                    
                    <div class="col-lg-12">
                        <div class="form-group col-lg-6">

                            <label>Họ:</label>
                            <input class="form-control col-lg-6" name="tbxHo" id="tbxHo" value="@(Model.strLastName)">
                        </div>
                        <div class="form-group col-lg-6">

                            <label>Tên:</label>
                            <input class="form-control col-lg-6" name="tbxTen" id="tbxTen" value="@(Model.strFirstName)">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group col-lg-4">

                            <label>Địa chỉ:</label>
                            <input class="form-control col-lg-4" name="tbxAddress" id="tbxAddress" value="@(Model.strAddress)">
                        </div>
                        <div class="form-group col-lg-4">

                            <label>Tên đường:</label>
                            <input class="form-control col-lg-4" name="tbxDistrict" id="tbxDistrict" value="@(Model.strDistrict)">
                        </div>
                        <div class="form-group col-lg-4">

                            <label>Thành phố:</label>
                            <input class="form-control col-lg-4" name="tbxCity" id="tbxCity" value="@(Model.strCity)">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group col-lg-6">

                            <label>Số điện thoại:</label>
                            <input class="form-control" id="tbxSDT" name="tbxSDT" value="@(Model.strSDT)">
                        </div>

                        <div class="form-group col-lg-6">

                            <label>Email:</label>
                            <input class="form-control" id="tbxEmail" name="tbxEmail" value="@(Model.strEmail)">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group col-lg-6">

                            <label>Chức vụ:</label>
                            <select class="form-control" name="sltKeyWordRole" id="sltKeyWordRole">
                                <option selected hidden value="@(Model.strRoleID)">@(Model.strRole)</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="form-group col-lg-12">
                            <button type="submit" class="btn btn-primary" id="btnXacNhan" onclick="return validationform()" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-check"></i>Xác nhận</button>
                            <button type="button" class="btn btn-default" id="btnBack" onclick="BackManageUpdate();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
                        </div>

                        
                    </div>
                }
            </div>

        </div>
        <!-- /.row (nested) -->
    </div>
    <!-- /.panel-body -->
</div>


@section Scripts
{
    <script type="text/javascript">
        var visiblePages = "@ViewBag.intVisiblePages";
    </script>

    <script src="~/Scripts/CustomScripts/Employees/InsertUpdateEmloyees.js"></script>
}

ProjectStudentManagement/ProjectStudentManagement/Views/Employees/Index.cshtml
@{
    ViewBag.Title = "Quản lý người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <input type="hidden" id="hdCurrentPage" name="hdCurrentPage" value="" />
        <input type ="hidden" id="hdCurRowBeforeDelOnScreen" name="hdCurRowBeforeDelOnScreen" value="" />

        <div class="row area-control">
            <div class="col-sm-12">
                <div class="form-inline">
                    <div class="form-group">
                        <input class="form-control" id="txtKeyWord" placeholder="Nội dung tìm kiếm" data-value="">
                    </div>
                    <button type="button" class="btn btn-primary" id="btnSearch"  data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-search"></i>Tìm kiếm</button>
                </div>
            </div>
        </div>
        @if (ViewBag.InsertPermission != false)
        {
            <div class="row area-control">
                <div class="col-sm-12">
                    <div class="form-inline">
                        <button type="button" class="btn btn-primary" id="btnInsert" onclick="InsertEmployees();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Thêm</button>
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-blue">
                    <div class="panel-heading">
                        quản lý giáo viên
                    </div>

                    <table width="100%" class="table table-striped table-bordered table-hover" id="tblEmployees">
                        <thead>
                            <tr>
                                <th style="width:3%;">STT</th>
                                <th style="width:8%;">Mã</th>
                                <th>Tên</th>
                                <th style="width:7%;">Xử lý</th>
                            </tr>
                        </thead>
                        <tbody id="ContentEmployees">
                            <tr><td colspan="12" class="table-content-null">Hiện không có nội dung</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="row" id="divPaging" style="display:none;">
            <div class="col-sm-6">
                <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Chỉ số phần tử <span id="page-from-index"></span> đến <span id="page-to-index"></span> trên <span id="total-record"><span>phần tử</div>
            </div>
            <div class="col-sm-6" id="divPagingIndex">
                <ul id="paging" class="pagination"></ul>
            </div>
        </div>
    </div>
</div>

<!-- Modal xác nhận xóa -->
<div class="modal fade" id="ModalConfirmDelete" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Xác nhận</h4>
            </div>

            <div class="modal-body">
                <div id="divMessage" data-id = ""></div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="DeleleEmployees();">Đồng ý</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var visiblepages = "@ViewBag.intVisiblePages";
    </script>
    <script src="~/Scripts/CustomScripts/Employees/ManageEmloyees.js"></script>
}