ProjectStudentManagement/ProjectStudentManagement/Controllers/SystemSettingsController.cs
using DAO;
using DTO;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ProjectStudentManagement.Controllers
{
    public class SystemSettingsController : Controller
    {
        public ActionResult Index()
        {
            //Kiểm tra xem người dùng có được xem(truy cập vào chức năng)
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLCD_V") == false)
            {
                return RedirectToAction("Login", "Home");
            }

            //Kiểm tra xem người dùng có được phép cập nhật
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLCD_U") == false)
            {
                ViewBag.EditPermission = false;
            }
            else
            {
                ViewBag.EditPermission = true;
            }
            SystemSettingsDTO dto = new SystemSettingsDTO();
            DataTable dtb = new SystemSettingsDAO().SearchSystemSettings();
            if (dtb != null && dtb.Rows.Count != 0)
            {
                dto.SettingID = dtb.Rows[0]["SettingID"].ToString();
                dto.MaximumAged = Convert.ToInt32(dtb.Rows[0]["MaximumAged"].ToString());
                dto.MinimumAged = Convert.ToInt32(dtb.Rows[0]["MinimumAged"].ToString());
                dto.MaximumStudentNumber = Convert.ToInt32(dtb.Rows[0]["MaxinumStudentNumber"].ToString());
                dto.StandardScore = Convert.ToDouble(dtb.Rows[0]["StandardScore"].ToString());
            }
            return View(dto);
        }

        [HttpPost]
        public ActionResult SystemSettingsUpdate(FormCollection frm)
        {

            try
            {
                int intTemp = 0;
                double doubTemp = 0;
                SystemSettingsDTO dto = new SystemSettingsDTO();

                dto.SettingID = frm["txtSettingID"];

                int.TryParse(frm["txtMinimumAged"], out intTemp);
                dto.MinimumAged = intTemp;

                int.TryParse(frm["txtMaximumAged"], out intTemp);
                dto.MaximumAged = intTemp;

                int.TryParse(frm["txtMaximumStudentNumber"], out intTemp);
                dto.MaximumStudentNumber = intTemp;

                double.TryParse(frm["txtStandardScore"], out doubTemp);
                dto.StandardScore = doubTemp;

                bool bolSuccess = new SystemSettingsDAO().UpdateSystemSettings(dto);

                if (bolSuccess == false)
                    return Json(new { iserror = true });

                return Json(new { iserror = false });
            }
            catch (Exception ex)
            {
                return Json(new { iserror = true });
            }

        }
    }
}

ProjectStudentManagement/ProjectStudentManagement/Views/SystemSettings/Index.cshtml
@{
    ViewBag.Title = "Quản lý khai báo cấu hình";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">QUẢN LÝ HỆ THỐNG</h4>
    </div>
</div>
@using (Html.BeginForm("SystemSettingsUpdate", "SystemSettings", FormMethod.Post, new { @id = "frmSystemSettingsUpdate" }))
{
    <input type="hidden" id="hdFormType" name="hdFormType" value="Update" />
    <div class="row">
        <div class="col-lg-12">
            <div class="col-lg-12">
                <div class="panel panel-blue">
                    <div class="panel-heading">
                        Cài đặt
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <form role="form">
                                    <div class="col-lg-12">
                                        <input class="form-control " id="txtSettingID" name="txtSettingID" value="@Model.SettingID" type="hidden" />

                                        <div class="form-group col-lg-12 form-inline">

                                            <label>Tuổi quy định: &nbsp;</label>
                                            <span> từ &nbsp;</span>
                                             <input class="form-control " id="txtMinimumAged" name="txtMinimumAged" placeholder="Vui lòng nhập tuổi tối thiếu" value="@Model.MinimumAged" style="width:50px"/>
                                             <span> đến &nbsp;</span>
                                             <input class="form-control " id="txtMaximumAged" name="txtMaximumAged" placeholder="Vui lòng nhập tuổi tối đa" value="@Model.MaximumAged"  style="width:50px">
                                        </div>

                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group col-lg-12 form-inline">
                                            <label>Sĩ số lớp tối đa: &nbsp; </label>
                                            <input class="form-control" id="txtMaximumStudentNumber" name="txtMaximumStudentNumber" placeholder="Vui lòng nhập sĩ số lớp tối đa" value="@Model.MaximumStudentNumber" style="width:50px">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group col-lg-12 form-inline">
                                            <label>Điểm chuẩn xếp loại:  &nbsp;</label>
                                            <input class="form-control" name="txtStandardScore" id="txtStandardScore" placeholder="Vui lòng chọn nhập điểm xếp loại" value="@Model.StandardScore" style="width:50px">
                                        </div>

                                    </div>
                                </form>
                            </div>

                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="row area-control">
        <div class="form-inline group-submit">
                @if (ViewBag.EditPermission)
                {
                    <button type="button" class="btn btn-primary" id="btnEdit" onclick="AllowEdit();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-pencil"></i>Chỉnh sửa</button>
                    <button type="button" class="btn btn-primary" id="btnUpdate" onclick="UpdateSystemSettings();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Lưu Thay đỗi</button>
                    <button type="button" class="btn btn-default" id="btnRefresh" onclick="RefreshPage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-refresh"></i>Làm lại</button>
                }
              <button type="button" class="btn btn-default" id="btnBack" onclick="BackManage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
       
         </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var visiblepages = "@ViewBag.intVisiblePages";
    </script>
    <script src="~/Scripts/CustomScripts/SystemSettings/ManageSystemSettings.js"></script>
}

ProjectStudentManagement/ProjectStudentManagement/Views/SystemSettings/SystemSettingsInsert.cshtml
@{
    ViewBag.Title = "Thêm khai báo cấu hình";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Nội dung chính</h4>
    </div>
</div>
@using (Html.BeginForm("InsertSystemSettings", "SystemSettings", FormMethod.Post, new { @id = "frmSystemSettingsInsert" }))
{
    <input type="hidden" id="hdFormType" name="hdFormType" value="Insert" />
    
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Giá trị</label>
                    <input class="form-control col-sm-9" style="width:60%;" id="txtValue" name="txtValue" maxlength="10">
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Mô tả</label>
                    <textarea rows="2" class="form-control col-sm-9" style="width:60%;" id="txtObject" name="txtObject" maxlength="50"></textarea>
                </div>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="row area-control">
        <div class="form-inline group-submit">
            <button type="button" class="btn btn-primary" id="btnInsert" onclick="InsertSystemSettings();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Thêm</button>
            <button type="button" class="btn btn-default" id="btnBack" onclick="BackManage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/Scripts/CustomScripts/SystemSettings/InsertUpdateSystemSettings.js"></script>
}

ProjectStudentManagement/ProjectStudentManagement/Views/SystemSettings/SystemSettingsUpdate.cshtml
@model DTO.SystemSettingsDTO
@{
    ViewBag.Title = "Cập khai báo cấu hình";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Nội dung chính</h4>
    </div>
</div>
@using (Html.BeginForm("UpdateSystemSettings", "SystemSettings", FormMethod.Post, new { @id = "frmSystemSettingsUpdate" }))
{
    <input type="hidden" id="hdFormType" name="hdFormType" value="Update" />
    <input type="hidden" id="hdSettingID" name="hdSettingID" />

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Mã cấu hình </label>
                    <input class="form-control col-sm-9" style="width:20%;" id="txtRoleID" name="txtRoleID" maxlength="50" value="" disabled>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Giá trị</label>
                    <input class="form-control col-sm-9" style="width:60%;" id="txtValue" name="txtValue" maxlength="10" value="">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Mô tả</label>
                    <textarea rows="2" class="form-control col-sm-9" style="width:60%;" id="txtObject" name="txtObject" maxlength="50"></textarea>
                </div>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="row area-control">
        <div class="form-inline group-submit">
            <button type="button" class="btn btn-primary" id="btnUpdate" onclick="UpdateSystemSettings();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Cập nhật</button>
            <button type="button" class="btn btn-default" id="btnBack" onclick="BackManage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/Scripts/CustomScripts/SystemSettings/InsertUpdateSystemSettings.js"></script>
}