ProjectStudentManagement/ProjectStudentManagement/Controllers/StudentsController.cs
using DAO;
using DTO;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ProjectStudentManagement.Controllers
{
    public class StudentsController : Controller
    {
        // GET: Students
        public ActionResult Index()
        {
            //Kiểm tra xem người dùng có được xem(truy cập vào chức năng)
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLHS_V") == false)
            {
                return RedirectToAction("Login", "Home");
            }

            //Kiểm tra xem người dùng có được phép insert
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLHS_I") == false)
            {
                ViewBag.InsertPermission = false;
            }
            else
            {
                ViewBag.InsertPermission = true;
            }
         
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            return View();
        }
        public ActionResult GetStudentsList(string strKeyWord, int intPageIndex = 0)
        {
            try
            {
                //Lấy cấu hình số dòng trên trang
                //int intPageSize = Convert.ToInt32(ConfigurationManager.AppSettings["RowPerPage"]);
                //Lấy config số trang hiển thị trên thanh phân trang
                int intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);
                int intTotalPages = 0;
                int intTotalRows = 0;

                //Gen HTML
                StringBuilder strHTML = new StringBuilder();

                DataTable dtb = new StudentsDAO().GetStudentsList(strKeyWord, intPageIndex, intVisiblePages);

                if (dtb != null && dtb.Rows.Count > 0)
                {
                    strHTML = GenHTMLStudents(dtb);
                    //Lấy tổng số lưởng dòng
                    intTotalRows = Convert.ToInt32(dtb.Rows[0]["TotalRows"]);
                    //Lấy tổng số lượng trang
                    intTotalPages = intTotalRows / intVisiblePages;
                    //Trường hợp số phần tử không chia hết cho intVisiblePages
                    if (intTotalRows % intVisiblePages != 0)
                        intTotalPages = intTotalPages + 1;
                }
                else
                {
                    strHTML.Append("<tr><td colspan='12' class='table-content-null'>Hiện không có nội dung</td></tr>");
                }
                return Json(new
                {
                    iserror = false,
                    content = Convert.ToString(strHTML),
                    totalpages = intTotalPages,
                    totalrows = intTotalRows
                });
            }
            catch
            {
                return Json(new { iserror = true });
            }
        }
        private StringBuilder GenHTMLStudents(DataTable dtb)
        {
            int intCountRow = dtb.Rows.Count;
            StringBuilder strbuilder = new StringBuilder();
            bool bPerDelete = true;
            //Kiểm tra xem người dùng có được phép delete
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLHS_D") == false)
            {
                bPerDelete  = false;
            }
            
            for (int i = 0; i < intCountRow; i++)
            {
                string StudentID = Convert.ToString(dtb.Rows[i]["StudentID"]).Trim();
                strbuilder.Append("<tr>");
                strbuilder.AppendFormat("<td>{0}</td>", dtb.Rows[i]["STT"]);
                strbuilder.AppendFormat("<td>{0}</td>", dtb.Rows[i]["StudentID"]);
                strbuilder.AppendFormat("<td>{0}</td>", dtb.Rows[i]["LastName"]);
                strbuilder.AppendFormat("<td>{0}</td>", dtb.Rows[i]["FirstName"]);
                strbuilder.AppendFormat("<td data-studentid='{0}'>", StudentID);
                strbuilder.AppendFormat("<span class='glyphicon glyphicon-pencil table-icon' data-name='Detail'></span>");
                if (bPerDelete == true)
                {
                    strbuilder.AppendFormat("<span class='glyphicon glyphicon-trash table-icon' data-name='Delete'></span>");

                }
                strbuilder.AppendFormat("</td>");
                strbuilder.Append("</tr>");
            }

            return strbuilder;
        }
        public ActionResult StudentsDetails(string strStudentID)
        {
            //Kiểm tra xem người dùng có được phép update
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLHS_U") == false)
            {
                ViewBag.EditPermission = false;
            }
            else
            {
                ViewBag.EditPermission = true;
            }
            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            StudentsDTO student = new StudentsDAO().GetStudentByID(strStudentID);
            var lstFamilyMember = new List<FamilyMemberDTO>();
            lstFamilyMember = new StudentsDAO().GetFamilyMemberListByID(strStudentID);
            student.lstFamilyMember = lstFamilyMember;
            Session["StudentDetailInfo"] = null;
            Session.Add("StudentDetailInfo", student);
            return View(student);
        }
        public ActionResult StudentsInsert()
        {
            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);
            DataTable dtb = new SystemSettingsDAO().SearchSystemSettings();
            if (dtb != null && dtb.Rows.Count != 0)
            {
                ViewBag.intMinimumAged = dtb.Rows[0]["MinimumAged"].ToString();
                ViewBag.intMaximumAged = dtb.Rows[0]["MaximumAged"].ToString();

            }
            else
            {
                ViewBag.intMinimumAged = "15";
                ViewBag.intMaximumAged = "20";
            }
            return View();
        }
        public ActionResult StudentsUpdate()
        {
            StudentsDTO student = new StudentsDTO();
            if (Session["StudentDetailInfo"] != null)
            {
                student = (StudentsDTO)Session["StudentDetailInfo"];
            }
            DataTable dtb = new SystemSettingsDAO().SearchSystemSettings();
            if (dtb != null && dtb.Rows.Count != 0)
            {
                ViewBag.intMinimumAged = dtb.Rows[0]["MinimumAged"].ToString();
                ViewBag.intMaximumAged = dtb.Rows[0]["MaximumAged"].ToString();

            }
            else
            {
                ViewBag.intMinimumAged = "15";
                ViewBag.intMaximumAged = "20";
            }
            return View(student);
        } 
        [HttpPost]
        public JsonResult StudentsInsert(FormCollection frm)
        {
            try
            {
                DateTime bod = new DateTime();
                StudentsDTO studentDTO = new StudentsDTO();
                studentDTO.FirstName = frm["txtFirstName"];
                studentDTO.LastName = frm["txtLastName"];
                studentDTO.Address = frm["txtAddress"];
                studentDTO.District = frm["txtDistrict"];
                studentDTO.Country = frm["txtCountry"];
                studentDTO.CityProvince = frm["txtCityProvince"];
                studentDTO.PostalCode = frm["txtPostalCode"];
                studentDTO.EmailAddress = frm["txtEmailAddress"];
                studentDTO.PhoneNumber = frm["txtPhoneNumber"];
                studentDTO.GraduationYear = String.Empty;
                DateTime.TryParse(frm["txtBirthday"], out bod);
                studentDTO.Birthday = bod;
                studentDTO.IsDeleted = false;
                studentDTO.Gender = frm["rdoGender"];
                studentDTO.Grade = frm["txtGrade"];
                studentDTO.YearOfAdmission = DateTime.Now.Year.ToString();
                List<FamilyMemberDTO> lstSubjectExemptRequest = Newtonsoft.Json.JsonConvert.DeserializeObject<List<FamilyMemberDTO>>(frm["hdListFamilyMember"]);

                bool bolSuccess = new StudentsDAO().StudentsInsert(studentDTO, lstSubjectExemptRequest);

                if (bolSuccess == false)
                    return Json(new { iserror = true });

                return Json(new { iserror = false });
            }
            catch (Exception ex)
            {
                return Json(new { iserror = true });
            }
        }
        [HttpPost]
        public JsonResult StudentsUpdate(FormCollection frm)
        {
            try
            {
                DateTime bod = new DateTime();
                StudentsDTO studentDTO = new StudentsDTO();
                studentDTO.StudentID = frm["txtStudentID"];
                studentDTO.FirstName = frm["txtFirstName"];
                studentDTO.LastName = frm["txtLastName"];
                studentDTO.Address = frm["txtAddress"];
                studentDTO.District = frm["txtDistrict"];
                studentDTO.Country = frm["txtCountry"];
                studentDTO.CityProvince = frm["txtCityProvince"];
                studentDTO.PostalCode = frm["txtPostalCode"];
                studentDTO.EmailAddress = frm["txtEmailAddress"];
                studentDTO.PhoneNumber = frm["txtPhoneNumber"];
                studentDTO.GraduationYear = frm["txtGraduationYear"];
                DateTime.TryParse(frm["txtBirthday"], out bod);
                studentDTO.Birthday = bod;
                studentDTO.IsDeleted = false;
                studentDTO.Gender = frm["rdoGender"];
                studentDTO.Grade = frm["txtGrade"];

ProjectStudentManagement/ProjectStudentManagement/Views/Students/Index.cshtml
@{
    ViewBag.Title = "Quản lý học sinh";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("StudentsUpdate", "Students", FormMethod.Post, new { @id = "frmStudentsUpdate" }))
{ }
<div class="row">
    <div class="col-lg-12">
        <input type="hidden" id="hdCurrentPage" name="hdCurrentPage" value="" />
        <input type="hidden" id="hdCurRowBeforeDelOnScreen" name="hdCurRowBeforeDelOnScreen" value="" />
        <div class="row area-control">
            <div class="col-sm-12">
                <div class="form-inline">
                    <div class="form-group">
                        <input class="form-control" id="txtKeyWord" placeholder="Nội dung tìm kiếm" data-value="">
                    </div>
                    <button type="button" class="btn btn-primary" id="btnSearch" onclick="GetStudentsList();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-search"></i>Tìm kiếm</button>
                </div>
            </div>
        </div>
        @if (ViewBag.InsertPermission)
        {
            <div class="row area-control">
                <div class="col-sm-12">
                    <div class="form-inline">
                        <button type="button" class="btn btn-primary" id="btnInsert" onclick="InsertStudent();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Thêm</button>
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-blue">
                    <div class="panel-heading">
                        Quản lý học sinh
                    </div>

                    <table width="100%" class="table table-striped table-bordered table-hover" id="tblEmloyeeRoles">
                        <thead>
                            <tr>
                                <th style="width:3%;">STT</th>
                                <th style="width:15%;">Mã Học Sinh</th>
                                <th>Họ </th>
                                <th>Tên</th>
                                <th style="width:7%;">Xử lý</th>
                            </tr>
                        </thead>
                        <tbody id="ContentStudents">
                            <tr><td colspan="12" class="table-content-null">Hiện không có nội dung</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="row" id="divPaging" style="display:none;">
            <div class="col-sm-6">
                <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Chỉ số phần tử <span id="page-from-index"></span> đến <span id="page-to-index"></span> trên <span id="total-record"><span>phần tử</div>
            </div>
            <div class="col-sm-6" id="divPagingIndex">
                <ul id="paging" class="pagination"></ul>
            </div>
        </div>
    </div>
</div>

<!-- Modal xác nhận xóa -->
<div class="modal fade" id="ModalConfirmDelete" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Xác nhận</h4>
            </div>

            <div class="modal-body">
                <div id="divMessage" data-id=""></div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="DeleleStudent();">Đồng ý</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var visiblepages = "@ViewBag.intVisiblePages";

    </script>
    <script src="~/Scripts/CustomScripts/Students/StudentManagement.js"></script>
}

ProjectStudentManagement/ProjectStudentManagement/Views/Students/StudentsDetails.cshtml
@model DTO.StudentsDTO
@{
    ViewBag.Title = "Thông tin học sinh";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Thông tin học sinh: <b>@((Model.LastName + " " + Model.FirstName).ToUpper())</b></h4>
    </div>
</div>
@using (Html.BeginForm("Update", "Students", FormMethod.Post, new { @id = "frmStudentsUpdate" }))
{
    <input type="hidden" id="hdStudentID" name="hdStudentID" value="@(Model.StudentID)" />

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"><b>Mã học sinh</b> </label>
                    <label class="header-control col-sm-9">@(Model.StudentID)</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"><b>Tên học sinh</b>  </label>
                    <label class="header-control col-sm-2">@(Model.FirstName + " " + Model.LastName)</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"> <b>Ngày Sinh</b> </label>
                    <label class="header-control col-sm-2">@(Model.Birthday.ToString("dd-MM-yyyy"))</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"> <b>Giới tính</b> </label>
                    @if (!String.IsNullOrEmpty(Model.Gender))
                    {
                        if (Model.Gender == "1")
                        {
                            <label class="header-control col-sm-2">Nam</label>
                        }
                        else
                        {
                            <label class="header-control col-sm-2">Nữ</label>

                        }

                    }
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"> <b>Trình độ</b></label>
                    <label class="header-control col-sm-2">@(Model.Grade)</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"> <b>Năm nhập học</b></label>
                    <label class="header-control col-sm-2">@(Model.YearOfAdmission)</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"><b>Năm Tốt Nghiệp </b> </label>
                    @if (String.IsNullOrEmpty(Model.GraduationYear) == true)
                    {
                        <label class="header-control col-sm-2">Chưa tốt nghiệp</label>
                    }
                    else
                    {
                        <label class="header-control col-sm-2">@Model.GraduationYear</label>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"> <b>Địa chỉ</b></label>
                    <label class="header-control col-sm-2">@(Model.Address)</label>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"> <b>Quận/Huyện</b> </label>
                    <label class="header-control col-sm-1">@(Model.District)</label>
                    <label class="header-control col-sm-2"> <b>Tỉnh/Thành</b> </label>
                    <label class="header-control col-sm-1">@(Model.CityProvince)</label>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2"> <b>Quốc Gia</b> </label>
                    <label class="header-control col-sm-1">@(Model.Country)</label>
                    <label class="header-control col-sm-2"> <b>Mã Bưu điện</b> </label>
                    <label class="header-control col-sm-1">@(Model.PostalCode)</label>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-blue">
            <div class="panel-heading">
                Danh Sách Người Thân
            </div>

            <table width="100%" class="table table-striped table-bordered table-hover" id="tblFamilyList">
                <thead>
                    <tr>
                        <th style="width:5%">STT</th>
                        <th>Họ và tên</th>
                        <th>Số điện thoại</th>
                        <th>Email</th>
                        <th style="width:10%">Mối quan hệ</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.lstFamilyMember.Count > 0)
                    {
                        for (int i = 0; i < Model.lstFamilyMember.Count; i++)
                        {
                            <tr>
                                <td data-name='STT'> @(i + 1)</td>
                                <td data-name='txtFamilyName'> @Model.lstFamilyMember[i].Name </td>
                                <td data-name='txtFamilyPhoneNumber'> @Model.lstFamilyMember[i].PhoneNumber </td>
                                <td data-name='txtFamilyEmailAddress'>  @Model.lstFamilyMember[i].EmailAddress </td>
                                <td data-name='txtRelationship'>
                                    @if (Model.lstFamilyMember[i].Relationship == "1")
                                    {
                                        <span>Cha Mẹ</span>
                                    }
                                    @if (Model.lstFamilyMember[i].Relationship == "2")
                                    {
                                        <span>Anh Chị</span>
                                    }
                                    @if (Model.lstFamilyMember[i].Relationship == "3")
                                    {
                                        <span>Cô Chú</span>
                                    }
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="12" class="table-content-null">Hiện không có nội dung</td>
                        </tr>

                    }

                </tbody>
            </table>
        </div>
    </div>
}

<div class="row">
    <div class="row area-control">
        <div class="form-inline group-submit">
            @if (ViewBag.EditPermission)
            {
                <button type="button" class="btn btn-primary" id="btnEdit" onclick="EditStudent();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-pencil"></i>Chỉnh sửa</button>
            }
            
            <button type="button" class="btn btn-default" id="btnBack" onclick="BackManage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
        </div>
    </div>
</div>

@section Scripts
{
    @*<script type="text/javascript">
            var visiblePages = "@ViewBag.intVisiblePages";
        </script>*@

    <script src="~/Scripts/CustomScripts/Students/StudentDetails.js"></script>
}