ProjectStudentManagement/ProjectStudentManagement/Controllers/EmloyeeRolesController.cs
using DAO;
using DTO;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ProjectStudentManagement.Controllers
{
    public class EmloyeeRolesController : Controller
    {
        #region Quản lý
        public ActionResult Index()
        {
            //Kiểm tra xem người dùng có được xem(truy cập vào chức năng)
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLNND_V") == false)
            {
                return RedirectToAction("Login", "Home");
            }

            //Kiểm tra xem người dùng có được phép thêm
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLNND_I") == false)
            {
                ViewBag.InsertPermission = false;
            }



            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            return View();
        }

        [HttpPost]
        public ActionResult SearchEmloyeeRoles(string strKeyWord, int intPageIndex = 0)
        {
            try
            {
                //Lấy cấu hình số dòng trên trang
                //int intPageSize = Convert.ToInt32(ConfigurationManager.AppSettings["RowPerPage"]);
                //Lấy config số trang hiển thị trên thanh phân trang
                int intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);
                int intTotalPages = 0;
                int intTotalRows = 0;

                //Gen HTML
                StringBuilder strHTMLEmloyeeRoles = new StringBuilder();

                DataTable dtbEmloyeeRoles = new EmloyeeRolesDAO().SearchEmloyeeRoles(strKeyWord, intPageIndex, intVisiblePages);

                if (dtbEmloyeeRoles != null && dtbEmloyeeRoles.Rows.Count > 0)
                {
                    strHTMLEmloyeeRoles = GenHTMLEmloyeeRoles(dtbEmloyeeRoles);
                    //Lấy tổng số lưởng dòng
                    intTotalRows = Convert.ToInt32(dtbEmloyeeRoles.Rows[0]["TotalRows"]);
                    //Lấy tổng số lượng trang
                    intTotalPages = intTotalRows / intVisiblePages;
                    //Trường hợp số phần tử không chia hết cho intVisiblePages
                    if (intTotalRows % intVisiblePages != 0)
                        intTotalPages = intTotalPages + 1;
                }
                else
                {
                    strHTMLEmloyeeRoles.Append("<tr><td colspan='12' class='table-content-null'>Hiện không có nội dung</td></tr>");
                }

                return Json(new { iserror = false, 
                                content = Convert.ToString(strHTMLEmloyeeRoles), 
                                totalpages = intTotalPages, 
                                totalrows = intTotalRows });
            }
            catch
            {
                return Json(new { iserror = true });
            }
        }

        private StringBuilder GenHTMLEmloyeeRoles(DataTable dtbPermission)
        {
            bool bPerEdit = true;
            bool bPerDelete = true;

            //Kiểm tra người dùng được xóa
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLNND_D") == false)
            {
                bPerDelete = false;
            }


            int intCountRow = dtbPermission.Rows.Count;
            StringBuilder strHTMLEmloyeeRoles = new StringBuilder();

            for (int i = 0; i < intCountRow; i++)
            {
                string strRoleID = Convert.ToString(dtbPermission.Rows[i]["RoleID"]).Trim();

                strHTMLEmloyeeRoles.Append("<tr>");
                strHTMLEmloyeeRoles.AppendFormat("<td>{0}</td>", dtbPermission.Rows[i]["STT"]);
                strHTMLEmloyeeRoles.AppendFormat("<td>{0}</td>", strRoleID);
                strHTMLEmloyeeRoles.AppendFormat("<td>{0}</td>", dtbPermission.Rows[i]["RoleName"]);
                string sEdit = "";
                string sDelete = "";
                if (bPerEdit != false)
                {
                    sEdit += "<span class='glyphicon glyphicon-pencil table-icon' data-name='Detail'></span>";
                }

                if (bPerDelete != false)
                {
                    sDelete += "<span class='glyphicon glyphicon-trash table-icon' data-name='Delete'></span>";
                }
                strHTMLEmloyeeRoles.AppendFormat("<td data-roleid='{0}'>" + sEdit + sDelete + "</td>", strRoleID);

                strHTMLEmloyeeRoles.Append("</tr>");
            }

            return strHTMLEmloyeeRoles;
        }

        public ActionResult EmloyeeRolesInsert()
        {
            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            return View();
        }

        public ActionResult EmloyeeRolesUpdate(string strRoleID)
        {
            //Kiểm tra người dùng được sửa
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLNND_U") == false)
            {
                return RedirectToAction("Login", "Home");
            }
            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            EmloyeeRolesDTO EmloyeeRoles = new EmloyeeRolesDAO().GetEmloyeeRolesByID(strRoleID);
            return View(EmloyeeRoles);
        }

        public ActionResult EmloyeeRolesDetail(string strRoleID)
        {
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLNND_V") == false)
            {
                return RedirectToAction("Login", "Home");
            }

            //Kiểm tra người dùng được sửa
            if (LoginDAO.CheckKeyPermission((string)Session["Username"], "PK_QLNND_U") == false)
            {
                ViewBag.UpdatePermission = false;
            }
            //Lấy config số trang hiển thị trên thanh phân trang
            ViewBag.intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);

            EmloyeeRolesDTO EmloyeeRoles = new EmloyeeRolesDAO().GetEmloyeeRolesByID(strRoleID);
            return View(EmloyeeRoles);
        }

        [HttpPost]
        public JsonResult DeleteEmloyeeRoles(string strRoleID)
        {
            try
            {
                string strMessageError = string.Empty;
                bool bolSuccess = new EmloyeeRolesDAO().DeleteEmloyeeRoles(strRoleID, ref strMessageError);

                if (bolSuccess == false)
                    return Json(new { iserror = true, message = strMessageError });

                return Json(new { iserror = false });
            }
            catch (Exception)
            {
                return Json(new { iserror = true, message = "" });
            }
        }
        #endregion

        #region Thêm
        [HttpPost]
        public ActionResult SearchPermission(string strKeyWord, int intPageIndex = 0)
        {
            try
            {
                //Lấy cấu hình số dòng trên trang
                int intPageSize = Convert.ToInt32(ConfigurationManager.AppSettings["RowPerPage"]);
                //Lấy config số trang hiển thị trên thanh phân trang
                int intVisiblePages = Convert.ToInt32(ConfigurationManager.AppSettings["visiblePages"]);
                int intTotalPages = 0;
                int intTotalRows = 0;

                //Gen HTML
                StringBuilder strHTMLPermission = new StringBuilder();

                DataTable dtbPermission = new EmloyeeRolesDAO().SearchPermission(strKeyWord, intPageIndex, intPageSize);

                if (dtbPermission != null && dtbPermission.Rows.Count > 0)
                {
                    strHTMLPermission = GenHTMLPermission(dtbPermission);
                    //Lấy tổng số lưởng dòng
                    intTotalRows = Convert.ToInt32(dtbPermission.Rows[0]["TotalRows"]);
                    //Lấy tổng số lượng trang
                    intTotalPages = intTotalRows / intVisiblePages;
                    //Trường hợp số phần tử không chia hết cho intVisiblePages
                    if (intTotalRows % intVisiblePages != 0)
                        intTotalPages = intTotalPages + 1;
                }
                else
                {
                    strHTMLPermission.Append("<tr><td colspan='12' class='table-content-null'>Hiện không có nội dung</td></tr>");
                }

                return Json(new
                {
                    iserror = false,
                    content = Convert.ToString(strHTMLPermission),
                    totalpages = intTotalPages,
                    totalrows = intTotalRows
                });
            }
            catch
            {
                return Json(new { iserror = true });
            }
        }

        private StringBuilder GenHTMLPermission(DataTable dtbPermission)
        {
            int intCountRow = dtbPermission.Rows.Count;
            StringBuilder strHTMLPermission = new StringBuilder();

            for (int i = 0; i < intCountRow; i++)
            {
                string strIDKey = Convert.ToString(dtbPermission.Rows[i]["IDKey"]).Trim();

                strHTMLPermission.AppendFormat("<tr id='tr_{0}'>", strIDKey);
                strHTMLPermission.AppendFormat("<td>{0}</td>", dtbPermission.Rows[i]["STT"]);
                strHTMLPermission.AppendFormat("<td data-name='idkey'>{0}</td>", strIDKey);
                strHTMLPermission.AppendFormat("<td data-name='description'>{0}</td>", dtbPermission.Rows[i]["KeyDescription"]);
                strHTMLPermission.AppendFormat("<td><span class='glyphicon glyphicon-plus table-icon' data-name='btnAddPermission' data-idkey='{0}'></span></td>", strIDKey);

ProjectStudentManagement/ProjectStudentManagement/Views/EmloyeeRoles/EmloyeeRolesDetail.cshtml
@model DTO.EmloyeeRolesDTO
@{
    ViewBag.Title = "Cập nhóm người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Nội dung chính</h4>
    </div>
</div>
@using (Html.BeginForm("UpdateEmloyeeRoles", "EmloyeeRoles", FormMethod.Post, new { @id = "frmEmloyeeRolesUpdate" }))
{
    <input type="hidden" id="hdRoleID" name="hdRoleID" value="@(Model.RoleID)" />

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Mã nhóm người dùng: </label>
                    <label class="header-control col-sm-9">@(Model.RoleID)</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Tên nhóm người dùng: </label>
                    <label class="header-control col-sm-9">@(Model.RoleName)</label>
                </div>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Phân quyền</h4>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-blue">
            <div class="panel-heading">
                quyền
            </div>

            <table width="100%" class="table table-striped table-bordered table-hover" id="tblPermission">
                <thead>
                    <tr>
                        <th style="width:8%;">Mã</th>
                        <th>Mô tả</th>
                    </tr>
                </thead>
                <tbody id="ContentPermission">
                    @if (Model.lstPermission != null && Model.lstPermission.Count() > 0)
                    {
                        for (int i = 0; i < Model.lstPermission.Count(); i++)
                        {
                            <tr id="tr_@Model.lstPermission[i].IDKey">
                                <td data-name="idkey">@Model.lstPermission[i].IDKey</td>
                                <td data-name="description">@Model.lstPermission[i].KeyDescription</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr><td colspan="12" class="table-content-null">Hiện không có nội dung</td></tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="row area-control">
        <div class="form-inline group-submit">
            @if(ViewBag.UpdatePermission != false)
            {
                <button type="button" class="btn btn-primary" id="btnEdit" onclick="EditEmloyeeRoles();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-pencil"></i>Chỉnh sửa</button>
            }
            
            <button type="button" class="btn btn-default" id="btnBack" onclick="BackManage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
        </div>
    </div>
</div>

@section Scripts
{
    @*<script type="text/javascript">
        var visiblePages = "@ViewBag.intVisiblePages";
    </script>*@

    <script src="~/Scripts/CustomScripts/EmloyeeRoles/DetailEmloyeeRoles.js"></script>
}

ProjectStudentManagement/ProjectStudentManagement/Views/EmloyeeRoles/EmloyeeRolesInsert.cshtml
@{
    ViewBag.Title = "Thêm nhóm người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Nội dung chính</h4>
    </div>
</div>
@using (Html.BeginForm("InsertEmloyeeRoles", "EmloyeeRoles", FormMethod.Post, new { @id = "frmEmloyeeRolesInsert" }))
{
    <input type="hidden" id="hdFormType" name="hdFormType" value="Insert" />
    <input type="hidden" id="hdListPermission" name="hdListPermission" value="" />
    <input type="hidden" id="hdCurrentPage" name="hdCurrentPage" value="" />

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Tên nhóm người dùng</label>
                    <input class="form-control col-sm-9" style="width:60%;" id="txtRoleName" name="txtRoleName" maxlength="50">
                </div>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Phân quyền</h4>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="row area-control">
            <div class="col-sm-12">
                <div class="form-inline">
                    <button type="button" class="btn btn-primary" id="btnInsertPermission" onclick="InsertPermission();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Thêm</button>
                    <div class="form-group">
                        <button type="button" class="btn btn-primary" id="btnInsertPermissionAll" onclick="InsertPermissionAll();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Thêm tất cả</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-blue">
            <div class="panel-heading">
                quyền
            </div>

            <table width="100%" class="table table-striped table-bordered table-hover" id="tblPermission">
                <thead>
                    <tr>
                        <th style="width:8%;">Mã</th>
                        <th>Mô tả</th>
                        <th style="width:3%;"></th>
                    </tr>
                </thead>
                <tbody id="ContentPermission">
                    <tr><td colspan="12" class="table-content-null">Hiện không có nội dung</td></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="row area-control">
        <div class="form-inline group-submit">
            <button type="button" class="btn btn-primary" id="btnInsert" onclick="InsertEmloyeeRoles();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Thêm</button>
            <button type="button" class="btn btn-default" id="btnBack" onclick="BackManage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
        </div>
    </div>
</div>

<!-- Modal quyền -->
<div class="modal fade" id="ModalPermission" role="dialog">
    <div class="modal-dialog" style="width:70%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" onclick="CloseInsertPermission();">&times;</button>
                <h4 class="modal-title">Thêm quyền</h4>
            </div>

            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row area-control">
                            <div class="col-sm-12">
                                <div class="form-inline">
                                    <div class="form-group">
                                        <input class="form-control" id="txtKeyWord" placeholder="Nội dung tìm kiếm">
                                    </div>
                                    <button type="button" class="btn btn-primary" id="btnSearch" onclick="SearchPermission();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-search"></i>Tìm kiếm</button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-blue">
                                    <div class="panel-heading">
                                        quyền
                                    </div>

                                    <table width="100%" class="table table-striped table-bordered table-hover" id="tblModelPermission">
                                        <thead>
                                            <tr>
                                                <th style="width:3%;">STT</th>
                                                <th style="width:8%;">Mã</th>
                                                <th>Mô tả</th>
                                                <th style="width:3%;"></th>
                                            </tr>
                                        </thead>
                                        <tbody id="ContentModelPermission">
                                            <tr><td colspan="12" class="table-content-null">Hiện không có nội dung</td></tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <div class="row" id="divPaging" style="display:none;">
                            <div class="col-sm-5">
                                <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Chỉ số phần tử <span id="page-from-index"></span> đến <span id="page-to-index"></span> trên <span id="total-record"><span>phần tử</div>
                            </div>
                            <div class="col-sm-7" id="divPagingIndex">
                                <ul id="paging" class="pagination"></ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" onclick="CloseInsertPermission();">Đóng</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var visiblepages = "@ViewBag.intVisiblePages";
    </script>

    <script src="~/Scripts/CustomScripts/EmloyeeRoles/InsertUpdateEmloyeeRoles.js"></script>
}

ProjectStudentManagement/ProjectStudentManagement/Views/EmloyeeRoles/EmloyeeRolesUpdate.cshtml
@model DTO.EmloyeeRolesDTO
@{
    ViewBag.Title = "Cập nhóm người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Nội dung chính</h4>
    </div>
</div>
@using (Html.BeginForm("UpdateEmloyeeRoles", "EmloyeeRoles", FormMethod.Post, new { @id = "frmEmloyeeRolesUpdate" }))
{
    <input type="hidden" id="hdFormType" name="hdFormType" value="Update" />
    <input type="hidden" id="hdListPermission" name="hdListPermission" value="" />
    <input type="hidden" id="hdCurrentPage" name="hdCurrentPage" value="" />
    <input type="hidden" id="hdRoleID" name="hdRoleID" value="@(Model.RoleID)" />

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Mã nhóm người dùng</label>
                    <input class="form-control col-sm-9" style="width:20%;" id="txtRoleID" name="txtRoleID" maxlength="50" value="@(Model.RoleID)" disabled>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="form-inline">
                    <label class="header-control col-sm-2">Tên nhóm người dùng</label>
                    <input class="form-control col-sm-9" style="width:60%;" id="txtRoleName" name="txtRoleName" maxlength="50" value="@(Model.RoleName)">
                </div>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Phân quyền</h4>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="row area-control">
            <div class="col-sm-12">
                <div class="form-inline">
                    <button type="button" class="btn btn-primary" id="btnInsertPermission" onclick="InsertPermission();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Thêm</button>
                </div>
            </div>
        </div>
        <div class="panel panel-blue">
            <div class="panel-heading">
                quyền
            </div>

            <table width="100%" class="table table-striped table-bordered table-hover" id="tblPermission">
                <thead>
                    <tr>
                        <th style="width:8%;">Mã</th>
                        <th>Mô tả</th>
                        <th style="width:3%;"></th>
                    </tr>
                </thead>
                <tbody id="ContentPermission">
                    @if (Model.lstPermission != null && Model.lstPermission.Count() > 0)
                    {
                        for (int i = 0; i < Model.lstPermission.Count(); i++)
                        {
                            <tr id="tr_@Model.lstPermission[i].IDKey">
                                <td data-name="idkey">@Model.lstPermission[i].IDKey</td>
                                <td data-name="description">@Model.lstPermission[i].KeyDescription</td>
                                <td><span class="glyphicon glyphicon-remove table-icon" data-name="btnRemovePermission" data-idkey="@Model.lstPermission[i].IDKey"></span></td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr><td colspan="12" class="table-content-null">Hiện không có nội dung</td></tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="row area-control">
        <div class="form-inline group-submit">
            <button type="button" class="btn btn-primary" id="btnUpdate" onclick="UpdateEmloyeeRoles();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-plus"></i>Cập nhật</button>
            <button type="button" class="btn btn-default" id="btnBack" onclick="BackManage();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-remove"></i>Bỏ qua</button>
        </div>
    </div>
</div>

<!-- Modal quyền -->
<div class="modal fade" id="ModalPermission" role="dialog">
    <div class="modal-dialog" style="width:70%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" onclick="CloseInsertPermission();">&times;</button>
                <h4 class="modal-title">Thêm quyền</h4>
            </div>

            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row area-control">
                            <div class="col-sm-12">
                                <div class="form-inline">
                                    <div class="form-group">
                                        <input class="form-control" id="txtKeyWord" placeholder="Nội dung tìm kiếm">
                                    </div>
                                    <button type="button" class="btn btn-primary" id="btnSearch" onclick="SearchPermission();" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Đang xử lý"><i class="fa fa-search"></i>Tìm kiếm</button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-blue">
                                    <div class="panel-heading">
                                        quyền
                                    </div>

                                    <table width="100%" class="table table-striped table-bordered table-hover" id="tblModelPermission">
                                        <thead>
                                            <tr>
                                                <th style="width:3%;">STT</th>
                                                <th style="width:8%;">Mã</th>
                                                <th>Mô tả</th>
                                                <th style="width:3%;"></th>
                                            </tr>
                                        </thead>
                                        <tbody id="ContentModelPermission">
                                            <tr><td colspan="12" class="table-content-null">Hiện không có nội dung</td></tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <div class="row" id="divPaging" style="display:none;">
                            <div class="col-sm-5">
                                <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Chỉ số phần tử <span id="page-from-index"></span> đến <span id="page-to-index"></span> trên <span id="total-record"><span>phần tử</div>
                            </div>
                            <div class="col-sm-7" id="divPagingIndex">
                                <ul id="paging" class="pagination"></ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" onclick="CloseInsertPermission();">Đóng</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var visiblepages = "@ViewBag.intVisiblePages";
    </script>

    <script src="~/Scripts/CustomScripts/EmloyeeRoles/InsertUpdateEmloyeeRoles.js"></script>
}